arr=np.array([1,2,3]) 
# print(arr)
# squared_arr = np.square(arr)
# print(squared_arr)
# arr=np.full([3,2],2)
# print(arr)
# arr3 = np.random.randint(0, 10, size=(2, 4))
# print(arr3)
# arr1 = np.arange(12).reshape(3, 4)

# # Flatten an array
# arr2 = arr1.flatten()

# # Transpose an array
# arr3 = arr1.transpose()

# # Concatenate arrays
# arr4 = np.concatenate((arr1, [arr3]), axis=1)

# print(arr1)
# print(arr2)
# print(arr3)
# print(arr4)